## 2. Randomised Experiments

### The ideal experiment

- From the previous section, we know that
$$\begin{aligned}
    E[Y|T=1] - E[Y|T=0] &= E[Y_1 - Y_0 | T=1] + (E[Y_0|T=1] - E[Y_0|T=0])
\end{aligned}$$

- The first term is the average treatment on the treated, and the second is the bias

- To make bias vanish, we need **randomised experiments**. 
    - Why? Because with proper randomisation, $(Y_0, Y_1) \perp T $
    - That is, the no-treatment-outcome $Y_0$ and treatment-outcome $Y_1$ are both independent of the treatment assignment $T$
    - Note, $Y_0$ and $Y_1$ are the **potential outcomes** not the observed outcomes

- In english, this simply means that the people in the treatment and control groups are the same, so any difference in outcomes between the two groups is attributable to the treatment $T$

- To show this:

$$\begin{aligned}
    E[Y_0 | T=0] &= E[Y_0 | T=1] \\
    &= E[Y_0] \\ \\

    \therefore E[Y|T=1] - E[Y|T=0] &= E[Y_1 - Y_0] \\
    &= \text{ATE}
\end{aligned}$$

### Example of Ideal Experiment

- During COVID, the question was asked if online learning was better than classroom learning
- Students were randomised classes such that some students get F2F lectures, and some get online classes, and a third group gets a mix of both

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('./data/2_online_classroom.csv')
data.head()

,gender,asian,black,hawaiian,hispanic,unknown,white,format_ol,format_blended,falsexam
0,0,0.0,0.0,0.0,0.0,0.0,1.0,0,0.0,63.29997
1,1,0.0,0.0,0.0,0.0,0.0,1.0,0,0.0,79.96000
2,1,0.0,0.0,0.0,0.0,0.0,1.0,0,1.0,83.37000
3,1,0.0,0.0,0.0,0.0,0.0,1.0,0,1.0,90.01994
4,1,0.0,0.0,0.0,0.0,0.0,1.0,1,0.0,83.30000

In [5]:
(
    data
    .assign(class_format = np.select(
        [data["format_ol"].astype(bool), data["format_blended"].astype(bool)],
        ["online", "blended"],
        default="face_to_face"
    ))
    .groupby(["class_format"])
    .mean()
)

,gender,asian,black,hawaiian,hispanic,unknown,white,format_ol,format_blended,falsexam
class_format,,,,,,,,,,
blended,0.550459,0.217949,0.102564,0.025641,0.012821,0.012821,0.628205,0.0,1.0,77.093731
face_to_face,0.633333,0.202020,0.070707,0.000000,0.010101,0.000000,0.717172,0.0,0.0,78.547485
online,0.542553,0.228571,0.028571,0.014286,0.028571,0.000000,0.700000,1.0,0.0,73.635263

- Because the class groups were randomised prior to the experiment, comparing the class format is literally as simple as taking the mean of the exam results!!! (78 vs 77 vs 73)

- The assumption is that all other characteristics are balanced across the other groups!!
    - But in this case, it seems like randomisation may have inadvertantly led to some bias (e.g. the `black` variable seems different for each of the groups!)